FROM node:20-alpine AS builder

WORKDIR /app
COPY package*.json ./
RUN NODE_OPTIONS="--max-old-space-size=1024" npm install --legacy-peer-deps --maxsockets 3
COPY . .
RUN NODE_OPTIONS="--max-old-space-size=1024" npm run build

FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]