// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {data} from '../models';
import {context} from '../models';
import {lo} from '../models';

export function AbortChatWithAgent():Promise<void>;

export function AbortSummaryStockNews():Promise<void>;

export function AddAllStockInfo(arg1:models.AllStockInfo):Promise<string>;

export function AddCronTask(arg1:data.FollowedStock):Promise<any>;

export function AddGroup(arg1:data.Group):Promise<string>;

export function AddPrompt(arg1:models.Prompt):Promise<string>;

export function AddPromptTemplate(arg1:models.PromptTemplate):Promise<string>;

export function AddStockGroup(arg1:number,arg2:string):Promise<string>;

export function AddTradingRecord(arg1:data.TradingRecord):Promise<number>;

export function AnalyzeSentiment(arg1:string):Promise<models.SentimentResult>;

export function AnalyzeSentimentWithFreqWeight(arg1:string):Promise<Record<string, any>>;

export function BatchDeleteAIResponseResult(arg1:Array<number>):Promise<string>;

export function BatchDeleteAllStockInfo(arg1:Array<number>):Promise<string>;

export function CalculateNextRunTime(arg1:string):Promise<string>;

export function CalculateNextRunTimes(arg1:string,arg2:number):Promise<Array<string>>;

export function ChatWithAgent(arg1:string,arg2:number,arg3:any,arg4:boolean,arg5:number,arg6:boolean):Promise<void>;

export function CheckFrequentTrading(arg1:string):Promise<Record<string, any>>;

export function CheckSponsorCode(arg1:string):Promise<Record<string, any>>;

export function CheckStockBaseInfo(arg1:context.Context):Promise<void>;

export function CheckUpdate(arg1:number):Promise<void>;

export function ClsCalendar():Promise<Array<any>>;

export function CreateCronTask(arg1:models.CronTask):Promise<string>;

export function DelPrompt(arg1:number):Promise<string>;

export function DeleteAIResponseResult(arg1:number):Promise<string>;

export function DeleteAiRecommendStocks(arg1:number):Promise<string>;

export function DeleteAllStockInfo(arg1:number):Promise<string>;

export function DeleteCronTask(arg1:number):Promise<string>;

export function DeletePromptTemplate(arg1:number):Promise<string>;

export function DeleteStockChangeHistory(arg1:number):Promise<string>;

export function DeleteTradingRecord(arg1:number):Promise<void>;

export function EMDictCode(arg1:string):Promise<Array<any>>;

export function EnableCronTask(arg1:number,arg2:boolean):Promise<string>;

export function ExecuteCronTaskNow(arg1:number):Promise<string>;

export function ExportConfig():Promise<string>;

export function FetchAiModels(arg1:string,arg2:string):Promise<Array<string>>;

export function FetchAndSaveMarketStatistic():Promise<void>;

export function Follow(arg1:string):Promise<string>;

export function FollowFund(arg1:string):Promise<string>;

export function GetAIResponseResult(arg1:string):Promise<models.AIResponseResult>;

export function GetAIResponseResultList(arg1:models.AIResponseResultQuery):Promise<models.AIResponseResultPageData>;

export function GetAiAssistantSession(arg1:string):Promise<models.AiAssistantSessionResp>;

export function GetAiConfigs():Promise<Array<data.AIConfig>>;

export function GetAiRecommendStocksList(arg1:models.AiRecommendStocksQuery):Promise<models.AiRecommendStocksPageData>;

export function GetAllConcepts():Promise<Array<string>>;

export function GetAllIndustries():Promise<Array<string>>;

export function GetAllMarkets():Promise<Array<string>>;

export function GetAllStockChangesWithPaging(arg1:number):Promise<data.StockChangesResponse>;

export function GetAllStockInfoById(arg1:number):Promise<models.AllStockInfo>;

export function GetAllStockInfoList(arg1:data.AllStockInfoQuery):Promise<data.AllStockInfoPageData>;

export function GetAllStocks(arg1:number,arg2:number,arg3:string,arg4:models.TechnicalIndicators):Promise<models.AllStocksResp>;

export function GetConfig():Promise<data.SettingConfig>;

export function GetCronTaskByID(arg1:number):Promise<models.CronTask>;

export function GetCronTaskList(arg1:models.CronTaskQuery):Promise<models.CronTaskPageResp>;

export function GetCronTaskTypes():Promise<Array<lo.Tuple2_string_string_>>;

export function GetEffectiveSponsorVip():Promise<Record<string, any>>;

export function GetFollowList(arg1:number):Promise<any>;

export function GetFollowedFund():Promise<Array<data.FollowedFund>>;

export function GetGroupList():Promise<Array<data.Group>>;

export function GetGroupStockList(arg1:number):Promise<Array<data.GroupStock>>;

export function GetHotStrategy():Promise<Record<string, any>>;

export function GetIndustryMoneyRankSina(arg1:string,arg2:string):Promise<Array<Record<string, any>>>;

export function GetIndustryRank(arg1:string,arg2:number):Promise<Array<any>>;

export function GetMarketStatisticByDate(arg1:string):Promise<Array<models.MarketStatistic>>;

export function GetMoneyRankSina(arg1:string):Promise<Array<Record<string, any>>>;

export function GetPromptTemplateList(arg1:models.PromptTemplateQuery):Promise<models.PromptTemplatePageData>;

export function GetPromptTemplates(arg1:string,arg2:string):Promise<any>;

export function GetRecentDaysMarketStatistic(arg1:number):Promise<Array<models.MarketStatistic>>;

export function GetSponsorInfo():Promise<Record<string, any>>;

export function GetStockChangeHistory(arg1:models.StockChangeHistoryQuery):Promise<models.StockChangeHistoryPageData>;

export function GetStockChanges(arg1:Array<number>,arg2:number,arg3:number):Promise<data.StockChangesResponse>;

export function GetStockCommonKLine(arg1:string,arg2:string,arg3:number):Promise<any>;

export function GetStockEastMoneyKLine(arg1:string,arg2:string,arg3:string,arg4:number):Promise<any>;

export function GetStockEastMoneyKLinePage(arg1:string,arg2:string,arg3:string,arg4:number,arg5:string):Promise<any>;

export function GetStockKLine(arg1:string,arg2:string,arg3:number):Promise<any>;

export function GetStockList(arg1:string):Promise<Array<data.StockBasic>>;

export function GetStockMinutePriceLineData(arg1:string,arg2:string):Promise<Record<string, any>>;

export function GetStockMoneyTrendByDay(arg1:string,arg2:number):Promise<Array<Record<string, any>>>;

export function GetStockRealTimePrice(arg1:string):Promise<Record<string, any>>;

export function GetTelegraphList(arg1:string):Promise<any>;

export function GetTimezone():Promise<Record<string, any>>;

export function GetTodayMarketStatistic():Promise<Array<models.MarketStatistic>>;

export function GetTradingRecordById(arg1:number):Promise<data.TradingRecord>;

export function GetTradingRecordList(arg1:data.TradingRecordListQuery):Promise<data.TradingRecordPageData>;

export function GetTradingRecordStatistics():Promise<data.TradingRecordStatistics>;

export function GetVersionInfo():Promise<models.VersionInfo>;

export function GetfundList(arg1:string):Promise<Array<data.FundBasic>>;

export function GlobalStockIndexes():Promise<Record<string, any>>;

export function GlobalStockIndexesReadable():Promise<string>;

export function Greet(arg1:string):Promise<data.StockInfo>;

export function HotEvent(arg1:number):Promise<any>;

export function HotStock(arg1:string):Promise<any>;

export function HotTopic(arg1:number):Promise<Array<any>>;

export function IndustryResearchReport(arg1:string):Promise<Array<any>>;

export function InitCronTasks():Promise<void>;

export function InitializeGroupSort():Promise<boolean>;

export function InvestCalendarTimeLine(arg1:string):Promise<Array<any>>;

export function LongTigerRank(arg1:string):Promise<any>;

export function NewChatStream(arg1:string,arg2:string,arg3:string,arg4:number,arg5:any,arg6:boolean,arg7:boolean):Promise<void>;

export function NewsPush(arg1:any):Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function ReFleshTelegraphList(arg1:string):Promise<any>;

export function RemoveGroup(arg1:number):Promise<string>;

export function RemoveStockGroup(arg1:string,arg2:string,arg3:number):Promise<string>;

export function SaveAIResponseResult(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number):Promise<void>;

export function SaveAiAssistantSession(arg1:string,arg2:Array<models.AiAssistantMessage>):Promise<void>;

export function SaveAsMarkdown(arg1:string,arg2:string):Promise<string>;

export function SaveImage(arg1:string,arg2:string):Promise<string>;

export function SaveStockChangesToHistory(arg1:Array<number>):Promise<string>;

export function SaveWordFile(arg1:string,arg2:string):Promise<string>;

export function SearchCronTasks(arg1:string):Promise<Array<models.CronTask>>;

export function SearchStock(arg1:string):Promise<Record<string, any>>;

export function SendDingDingMessage(arg1:string,arg2:string):Promise<string>;

export function SendDingDingMessageByType(arg1:string,arg2:string,arg3:number):Promise<string>;

export function SetAlarmChangePercent(arg1:number,arg2:number,arg3:string):Promise<string>;

export function SetCostPriceAndVolume(arg1:string,arg2:number,arg3:number):Promise<string>;

export function SetStockAICron(arg1:string,arg2:string):Promise<void>;

export function SetStockSort(arg1:number,arg2:string):Promise<void>;

export function SetTradingPrice(arg1:string,arg2:number,arg3:number,arg4:number,arg5:number):Promise<string>;

export function ShareAnalysis(arg1:string,arg2:string):Promise<string>;

export function ShareText(arg1:string,arg2:string):Promise<string>;

export function StockNotice(arg1:string):Promise<Array<any>>;

export function StockResearchReport(arg1:string):Promise<Array<any>>;

export function SummaryStockNews(arg1:string,arg2:number,arg3:any,arg4:boolean,arg5:boolean,arg6:string,arg7:string):Promise<void>;

export function UnFollow(arg1:string):Promise<string>;

export function UnFollowFund(arg1:string):Promise<string>;

export function UpdateAiRecommendStocksAlert(arg1:number,arg2:boolean):Promise<string>;

export function UpdateConfig(arg1:data.SettingConfig):Promise<string>;

export function UpdateCronTask(arg1:models.CronTask):Promise<string>;

export function UpdateGroupSort(arg1:number,arg2:number):Promise<boolean>;

export function UpdatePromptTemplate(arg1:models.PromptTemplate):Promise<string>;

export function UpdateTradingRecord(arg1:data.TradingRecord):Promise<void>;

export function ValidateCronExpr(arg1:string):Promise<string>;
